# declarative setup of Argo CD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/thetkpark/try-argo-cd.git
    targetRevision: HEAD
    path: dev # which path in repo to use
  destination:
    server: https://kubernetes.default.svc  # Endpoint of K8s API Server (Use internal DNS because Argo CD is running in the cluster)
    namespace: myapp # which namespace Argo CD should manage

  syncPolicy:
    syncOptions:
    - createNamespace=true

    automated:
      selfHeal: true # enable automatic sync when the live cluster's state deviates from the state defined in Git
      prune: true # prune any changes that differ from git repo
