apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-depl
spec:
  selector:
    matchLabels:
      app: ghost
  replicas: 2
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost
        ports:
        - containerPort: 80
